### ISSUE TITLE
README instructions didn't work

### ISSUE THREAD

**Issue by JapanYoshi** [DanWahlin/ES6Samples#7]
I can't use these samples

**Comment by DanWahlin** [comment]
I can help but you need to provide some details on the problem you're running into. Simple saying, "I can't use these samples" doesn't help at all. If it's just needing more detail (on installing Gulp for example) I can provide that. I'd need more detail though.

**Comment by JapanYoshi** [comment]
Example: Run `npm install` where? How? With what arguments? What will it do? Do I need to run any other commands? What programs are prerequisites for this? For something that's targeted towards beginners, it's really not beginner-friendly...

**Comment by DanWahlin** [comment]
Everything you're asking about is in the readme actually. You'll run "npm install" at the root of the project in the command window - no additional commands, just `npm install`. This is a common command for JavaScript projects so understanding the tools is required in order to work with ES6/ES2015 (there's an implicit assumption in this project and nearly all JavaScript open source projects out there that you know those tools since they're common in the JavaScript world). 

It sounds like you might be new to Node.js so here's a quick overview to provide a jumpstart for you. There are many tutorials on getting started out there on the web if you're interested though - that's not something this type of project can provide.

1. Once you've installed Node.js you'll have a tool called `npm` and a tool called `node` available that you can use from the command-line. 
2. npm can be used to do things like install "packages" (additional code someone else wrote) to perform various tasks. In project we have to convert ES2015 code to ES5 so it'll work in all browsers, so one of the packages installed is called Babel.
3. When you run npm install (no additional commands needed - just type what the readme says) it'll look in the package.json file for packages that should be installed and install them.
4. This project relies on Gulp as well (a Node.js tool/package) to perform the task of converting ES2015 to ES5 code. The readme covers installing that.
5. You then type "gulp" in the command window (make sure you're at the root of the project - no additional commands, just `gulp`) and that will convert the code and watch for any changes.

Hopefully that helps. If you need more help than that then I'd recommend going through a Node.js tutorial and learning more about npm and how it works.
